### PR TITLE
Improve keyword input focus style and contrast ratio

### LINKED ISSUE #706: Keyword input field has no focus style
See https://github.com/Yoast/yoast-components/commit/52e9daeb701bc063dd87c627802471e10f0d7300

While all the fields in the meta box, for example the snippet editor ones, and the synonyms one on premium, have a proper focus style, the `KeywordField` has no focus style at all.

Focus indication is a basic a11y requirement, and [seems it was intentionally reset](https://github.com/Yoast/yoast-components/commit/52e9daeb701bc063dd87c627802471e10f0d7300) with some `!important` CSS declarations.

Also, the `hasError` class won't work because the border and outline are already reset, so the color change on the border and outline won't produce any effect.w

### PR DESCRIPTION
**Pull request by afercia**
## Summary

This PR can be summarized in the following changelog entry:

- Improves the keyword input field focus style and contrast ratio

## Test instructions
- on the standalone app, yarn start go to localhost:3333
- go to the "Keyword" tab 
- verify the focus style of the keyword input field (without and with remove icon) work correctl
- verify the remove icon has a focus style

screen shot 2018-08-09 at 18 52 09

Note: on the standalone app the fields will show the native browser focus style: blue outline on webkit and none on Firefox. 

Also, verify the `.had-error` CSS class works properly when there's an error (you can alter the code or add the CSS class in your browser inspector:

screen shot 2018-08-09 at 19 04 43

To test the actual focus style in the metabox:
- yarn link yoast-components on the premium plugin
- build the js in the premium folder and in the root
- edit a post, go to the plugin meta box
- verify the focus keyword field has a nice focus style
- verify the additional focus keyword field has a nice focus style
- verify the remove icon button has a focus style

Fixes #706

### CODE REVIEW

**Comment by afercia** [comment]
Needs to be checked in RTL.

**Comment by afercia** [comment]
Please check also in RTL:

screen shot 2018-08-10 at 09 53 24

**Comment by afercia** [comment]
Because we all love Edge and IE, we should always remember these browsers display a native `X` on the input fields. On the left: Edge, on the right: IE11:

screenshot 54

it can be reset with some proprietary CSS property.

**Comment by dutchmartin** [comment]
Acceptance done 👍

**Pull request merged**
