### PR TITLE
Add a component to render a button with icon and text label

### LINKED ISSUE #627: Create a sidebar button component
Create a sidebar button component that can be used for the following things: 
schermafbeelding 2018-06-28 om 09 02 23
NB. Please think about a better name than sidebarButton, if possible.

!! **Branch from feature/content-analysis-in-sidebar** !!

#### Context of the buttons:
sidebar 7 expanded

Needs #649

### LINKED ISSUE #632: Buttons: addHoverStyle, addFocusStyle, addActiveStyle default props have no effect
Continuing the investigation on button while attempting to build a test page for buttons, see #631 ,I've noticed that after the changes in https://github.com/Yoast/yoast-components/commit/d63570b1568902322370beb09196bd3d0985d803 the default props for the buttons hover, focus, and active styles don't have any effect.

Previously, these styles used the colors from the color palette. Now, they use colors from the props, with some default values set as `defaultProps`. However, these defaultProps are set on the wrapping styling functions: they're not component so props won't work there.

See for example https://github.com/Yoast/yoast-components/blob/11dd35f4aa9a3a23994e22294581e83240172852/composites/Plugin/Shared/components/Button.js#L99 where `props` is undefined within that function.

Instead, these default props should be set on the Button component itself, or any other component that makes use of `addHoverStyle()`, `addFocusStyle()`, and `addActiveStyle()`. See for example the `YoastButton` which makes use of props in its `addButtonStyles()` function, but the `textColor` is set to the component itself: https://github.com/Yoast/yoast-components/blob/11dd35f4aa9a3a23994e22294581e83240172852/composites/Plugin/Shared/components/YoastButton.js#L137

As a consequence, all buttons that are intended to rely on the default props, don't display any style change for the hover, focus, and active states. For example, the "Edit snippet" button is supposed to change the following styles when hovered:
- color (it works because it uses a color from `$colors`)
- background (doesn't work, it's a prop)
- border (doesn't work, it's a prop)

This is how it looks like on hover:

now

And this is how it's supposed to look like:

should

Note: this applies also to the `LinkButton` component, it should set the default props to `BaseLinkButton`.

Needs #649

### PR DESCRIPTION
**Pull request by afercia**
## Summary

This PR can be summarized in the following changelog entry:

* Added a `IconLabelledButton` component to render a button with visible textual label

In order to re-use some wrapper functions used for the buttons (addHoverStyle, addFocusStyle, addActiveStyle) I had to fix #632 first. To test this part, please follow these steps:
- on the **develop** branch, go in the buttons test page
- check the first 7 buttons and verify:
  - on hover, there's no visible change other than the text color
  - on focus, there's no visible change other than the text color and the focus blue "outline"
  - on active (while clicking the button), there's no visible change other than the text color and the focus blue "outline"
- switch to this branch and verify:
  - on hover, also the background and border change 
  - on focus, also the background changes 
  - on active, the buttons look "pressed", with an inset box-shadow

With regards to the new `IconLabelledButton` button, I've added it to the Buttons test page so you can just run the standalone app (`yarn start`) and go to localhost:3333. See in the screenshot below:

screen shot 2018-07-09 at 10 23 54

A few questions:
- should the button text be bold? Unsure if the semi-bold in the screenshot in the issue is just how macOS renders text or if it's a real bold
- is there any case where we'd want the icon and text of different colors? I guess no, and if so I'd try to slightly simplify the props
- do we need more props (e.g. icon size)?
- in the issue there's no design for the hover/focus/active states, so I've implemented just a basic focus style and there are already props for the states
- any better idea for the component's name `IconLabelledButton`?

Fixes #627 
Fixes #632 

Needs #649

### CODE REVIEW

**Comment by maartenleenders** [comment]
CR 👍

**Comment by maartenleenders** [comment]
Acceptance 🚧 

See video!
Click focus (active?) does not seem to work in Safari and Firefox. Focussing via the TAB key does show the blue border. Chrome works fine.


stylingerrors

**Comment by afercia** [comment]
Well, this is due to the different way browsers apply the `:focus` and `:active` states when _clicking_ a button. Testing on the mac:

While clicking a button (and keeping the mouse/trackpad pressed), Chrome considers the button "focused" and "active". Other browsers don't, and they just apply the "active" style, if any.

To confirm the different behavior, add this to the base button style:
```
&:focus:active {
	background: yellow !important
}
```

Chrome applies the yellow background, this means it considers the button focused and active at the same time. Firefox and Safari don't.

To add more fun, the behavior is also different when activating the button with the Spacebar:
- tab to the button and press Spacebar
- Chrome and Safari show the yellow background
- Firefox doesn't

Worth noting the active style can be passed via props, so it can be made the same of the focus style, if needed. By default, there's no active style.

For completeness, I guess we need to add the text color prop to the active style so all the three state can handle `color`, `background-color`, and `border-color`.

The `box-shadow` is hardcoded, I haven't touched that but it can be tweaked if need be.

**Comment by afercia** [comment]
Please also notice the few questions in the first comment, most of them related to design /Cc @hedgefield

**Comment by hedgefield** [comment]
- The text is fine, font weight can be based on default links.
- No different colors between text and icon are needed.
- A prop for icon size is also not needed.
- I like the custom focus indicator you made. Might be nicer if the color was blue, to match the text color. So on hover it might invert the colors basically, blue button shape and white text.

**Comment by afercia** [comment]
In the last commit:
- the icon color now uses the text color prop
- added a hover style with inverted colors
- matched the active style with the hover style
- improved the order of the rendered style elements

There's still one thing to address though, due to inconsistency across browsers.

**Comment by afercia** [comment]
OK so I've spent some more time debugging and found out that to minimize inconsistencies across browsers it's best to match the hover, focus, and active styles, at least for the colors.

More importantly, there's a fundamental downside in the way we're using the `addHoverStyle`, `addFocusStyle`, and `addActiveStyle` functions together with the default props. In native CSS, it would be extremely easy to get what we need. Specifically, we need the states pseudo classes printed out in a specific order:

:hover
:focus (must override :hover)
:active (must override :hover and :focus)

Instead, with styled-components and the above functions, things work differently. For example, when passing props for the `:hover` state, the styles generated via default props get printed out first and the style generated via the passed prop gets printed out later. We'll have something like this, in this order:
```
default `active` style coming from default props:
.ldDEIv:active{color:#fff;background-color:#0066cd;box-shadow:inset 0 2px 5px -3px rgba( 0,0,0,0.5 );}

`hover` style passed via props:
.gyHKFR:hover{color:#fff;background-color:#a4286a;}
```

Now, when a button is hovered and pressed, the `:hover` style will prevail and that's not what we want. I guess this is just how styled-components works, it prints the default style before the styles passed via props, which makes generally sense because custom styles must override the default ones. Unfortunately, in the case of states pseudo classes this can lead to unwanted results.

So, when passing custom props, there's the need to pass _all_ the props related to the states.

**Comment by maartenleenders** [comment]
CR 👍

**Comment by maartenleenders** [comment]
Acceptance 👍

**Pull request merged**
