### PR TITLE
Fix react-hot-loader entry in package.json.

### PR DESCRIPTION
**Pull request by afercia**
Adds missing dot in the react-hot-loader entry in package.json after #174

### CODE REVIEW

**Comment by afercia** [comment]
screen shot 2017-07-27 at 10 27 24

**Comment by Xyfi** [comment]
Hmm funny. That's the version I selected but apparently yarn put the "dotless" version into package.json anyway.

**Comment by IreneStr** [comment]
@afercia Your build is failing 😬

**Comment by afercia** [comment]
@IreneStr yeah I know. Travis broke the internet! 👽

**Comment by afercia** [comment]
One of the builds still fails, `yarn test -- --coverage` runs locally and on the other build. /cc @atimmer

**Comment by Xyfi** [comment]
Well, upgrading `jest` did it. But why it makes this build fail and all the other PR's not is a mistery to me.

**Pull request merged**
