### PR TITLE
CSS for responsive video.

### LINKED ISSUE #82: Onboarding Wizard responsive video
See https://github.com/Yoast/wordpress-seo/pull/5643

We need to add CSS to make the vireo in the last step responsive.

### PR DESCRIPTION
**Pull request by afercia**
Fixes #82 

Inspired by fitvids.js please notice this is a hardcoded solution, meaning it relies on the known aspect ratio of the video (560x315 = 16:9) and the CSS is based on that.

Depends on https://github.com/Yoast/wordpress-seo/pull/5643

### CODE REVIEW

**Comment by terw-dan** [comment]
CR :+1:

**Comment by rensw90** [comment]
Acceptance done 👍

**Comment by afercia** [comment]
Sorry, not sure if this should be merged in the 1.0 release branch too

**Comment by rensw90** [comment]
You're right, this should be merged into the release branch also. I'll fix that right now.

**Comment by afercia** [comment]
Thanks, sorry my mistake

**Pull request merged**
