### PR TITLE
Added color value for no-index

### LINKED ISSUE #446: Widget bullet for noindexed post is not blue
This issue is a copy from: 
https://github.com/Yoast/wordpress-seo/issues/9217

The color of the bullets is returned wordpress-seo here: 
https://github.com/Yoast/wordpress-seo/blob/trunk/js/src/wp-seo-dashboard-widget.js#L39

But the css-color value is taken from yoast-components/style-guide/colors.json and this is the file where the color value (#1e8cbe) for noindex needs to be added.

### PR DESCRIPTION
**Pull request by Dieterrr**
## Summary

This PR can be summarized in the following changelog entry:

* Adds `"$color_noindex":"#1e8cbe"` to `colors.json` so that the bullets for noindexed posts will be blue instead of the default grey. 

## Test instructions

This PR can be tested by following these steps:

* Set one or more posts to noindex (Allow search engines to show this Post in search results?-->No)
* In your Yoast SEO post overview (In dashboard) the color of bullets labeled "Posts that should not show up in search results" or "Posts that are set to “noindex” should be blue instead of grey. 

Fixes #446

### CODE REVIEW

**Comment by atimmer** [comment]
`colors.json` is generated based on `_colors.scss`: https://github.com/Yoast/yoast-components/blob/develop/grunt/config/scss_to_json.js. So both need to change at the same time.

**Comment by Dieterrr** [comment]
Tnx, added the color to the _colors.scss file. Discussed with design team for name and guidelines.

**Comment by afercia** [comment]
CR 👍 

In wordpress-seo, I'd suggest to update the docblock for `getColorFromScore()` as it doesn't mention there's also `noindex` as possible value:
`* @param {string} score The score, expected to be 'na', 'bad', 'ok', 'good'.`

The dashboard widget looks ok 👍 

screen shot 2018-03-20 at 14 36 58

**Comment by Dieterrr** [comment]
Good point Andrea, I have just added this in wordpress-seo.

**Comment by jcomack** [comment]
Acceptance test done 👍

**Pull request merged**
