### PR TITLE
Use replacevar labels (nicenames) in suggestions

### LINKED ISSUE #577: Use snippet variables nicenames when selecting them in the mentions plugin
In https://github.com/Yoast/yoast-components/pull/566, Nicenames are introduced for snippet variables. But these nicenames weren't used when selecting a snippet variable in the mentions plugin. So this needs to be added.

yoast_components-2

Needs https://github.com/Yoast/wordpress-seo/pull/10065
Needs https://github.com/Yoast/yoast-components/issues/577

### PR DESCRIPTION
**Pull request by maartenleenders**
## Summary

This PR can be summarized in the following changelog entry:

* Replacevar suggestions now use nicenames rather than raw replacevariable names.

## Test instructions

This PR can be tested by following these steps:

* Test whether the dropdown suggestion list (after typing `%`) uses nicenames, and will fill the nicename into the editor field.
* Verify that the preview still replaces the variable with the correct value.
* Save and load posts, and enter replacevars by just typing `%%title%%` etc., and see that that functionality also still works (so without using the mention/suggestions).

Fixes #577 
Requires https://github.com/Yoast/wordpress-seo/pull/10065 (for custom field replacevars)

### CODE REVIEW

**Comment by danielFangstrom** [comment]
CR 👍

**Comment by danielFangstrom** [comment]
ACC 🚧 
When typing a non-letter character after the percentage sign, the suggestions keep popping up, regardless of where the cursor is. Nothing but selecting an option from the suggestions will stop it from popping up.

**Comment by maartenleenders** [comment]
The suggestions that kept coming up was because the Mention plugin doesn't like the suggestions being tampered with in the render function. I don't know why. @igorschoester suggested it might have to do with changing pointers.

We moved suggestion management to the state, and manage that state in the `onSearchChange` and `componentWillReceiveProps`. This pleased the mention plugin ;).

**Comment by boblinthorst** [comment]
CR: ok 👍

**Comment by maartenleenders** [comment]
@CarolineGeven yes, that is specifically what this PR fixes. See https://github.com/Yoast/yoast-components/issues/577

**Comment by danielFangstrom** [comment]
ACC 🚧 
Custom fields with spaces in the name creates duplicate entries in the suggestions, which in turn causes React to throw a warning.

**Comment by maartenleenders** [comment]
Fixed in https://github.com/Yoast/wordpress-seo/pull/10065

**Comment by danielFangstrom** [comment]
ACC 🚧 (because of related PR)

**Comment by maartenleenders** [comment]
Related PR issues will be fixed in https://github.com/Yoast/wordpress-seo/issues/10098

**Comment by danielFangstrom** [comment]
ACC 👍

**Pull request merged**
