### PR TITLE
Standard color palette and colors review

### LINKED ISSUE #106: Create a standardized color palette
In https://github.com/Yoast/wordpress-seo/issues/5759 we have discussed creating a standardized color palette. We should put this in the `yoast-components` repository per https://github.com/Yoast/wordpress-seo/issues/5759#issuecomment-251087546.

I think we should create a `style-guide` folder in which we put everything regarding the style guide. So maybe a `README.md` discussing the actual style guide and both a `colors.scss` and a `colors.json`.

cc @Mijke, @afercia

### PR DESCRIPTION
**Pull request by afercia**
Fixes #106 

Just a first pass for now, still have to create a folder where to put things (maybe create a README.md) and a `colors.json` but need to share the current progress to discuss a few things. I guess conflicts can be fixed later.

Things that need a decision/feedback:
- naming conventions
- underscore or hyphen? 😬 
- what to do about rgba greys (mainly box-shadows)
- should the color schemes be included in the main colors file or be separated in their own file?

The base idea is to establish a general, standard, colors palette that can be used everywhere and then re-map the currently used colors to the palette-colors.

Platform-specific colors (e.g. WordPress specific link colors) shouldn't be part of the palette.

Worth noting I'm updating stuff also on YoastSEO.js on a local branch.

### CODE REVIEW

**Comment by afercia** [comment]
After some research, I'm trying `grunt-scss-to-json` to generate the `colors.json` file. See details:
https://www.npmjs.com/package/grunt-scss-to-json
https://github.com/ryanbahniuk/grunt-scss-to-json

There are more advanced tools (also a ruby gem and couple of JS modules) also for the other way around (JSON -> scss) but this one is simple and seems to work for our needs.
I'd defer to @atimmer for the final decision :)

**Comment by afercia** [comment]
Tested and re-tested, there are things that can be improved of course but I think it's time for a first code review and feedback :)

Side note, there are a few things to document, should they go in the readme file?

**Comment by andizer** [comment]
CR Done 👍

**Comment by terw-dan** [comment]
Acceptance 👍

**Pull request merged**
