### PR TITLE
Port yoast-premium-components to yoast-components

### PR DESCRIPTION
**Pull request by Xyfi**
## Summary

This PR can be summarized in the following changelog entry:

* Adds the `KeywordSuggestion` component
* Adds the `LinkSuggestion` component

## Test instructions

This PR can be tested by following these steps:

* Test with the following branch in `wordpress-seo-premium`: `port-yoast-premium-components-to-yoast-components`.
* Make sure the link suggestions and keyword suggestions work as expected.

### CODE REVIEW

**Comment by andizer** [comment]
@Xyfi Can you resolve the merge conflicts

**Comment by jcomack** [comment]
CR done 👍 

I also attempted to acceptance test this, but ran into a minor issue regarding translation files. That issue can only be fixed by https://github.com/Yoast/wordpress-seo/pull/9672, which is still waiting to be merged.

Until then, I'm going to set this issue to blocked and retry an acceptance test at a later time.

**Comment by andizer** [comment]
Merge conflicts are resolved.

**Comment by boblinthorst** [comment]
Acceptance: Tested internal link suggestions and keyword suggestions/prominent words. Both seemed to work fine, though judging the quality of those suggestions is difficult. At the very least, I can say the prominent words selects words that are definitely used in the text, and the linking suggestion is able to make very obvious links between posts, and suggest linking them internally. It is very slow though.

**Pull request merged**
