### PR TITLE
Changed SearchDetail buttons to yoast buttons

### LINKED ISSUE #305: Implement correct buttons in Algolia searcher
See #198 for the correct buttons.

### PR DESCRIPTION
**Pull request by Xyfi**
## Test instructions

This PR can be tested by following these steps:

* Open a KB article in the AlgoliaSearcher, inspect the buttons at the top.

## Known issues

There is no drop shadow on the angle icons in the buttons. This is a known issue and has been discussed with @hedgefield. 

Fixes #305

### CODE REVIEW

**Comment by Xyfi** [comment]
Waiting for #308

**Comment by IreneStr** [comment]
CR and acceptance done 👍

**Comment by boblinthorst** [comment]
Code reviewed the last commits by Irene at her request, they seemed fine.

**Comment by IreneStr** [comment]
CR and acceptance done 👍

**Pull request merged**
