### PR TITLE
Onboarding Wizard styling improvements and responsive view

### LINKED ISSUE #72: Onboarding Wizard: styling improvements and responsive view
Agreed on Slack to:
- increase white space in the step container
- set a max width for all the wizard
- increase a bit the default line-height
- make also the heading h2 purple and lighter
- improve the responsive view

proposal:
screen shot 2016-09-14 at 16 22 18

### PR DESCRIPTION
**Pull request by afercia**
Fixes #72 

Max-width set at 1660px, can't test it properly I can just zoom in to emulate a bigger screen, see below:
screen shot 2016-09-14 at 19 24 43

Responsive view: 

screen shot 2016-09-14 at 18 41 48

Worth noting the "stepper" causes some troubles, see for example the visible text when the buttons are close to the right edge of the screen:

screen shot 2016-09-14 at 19 07 18

not to mention the horizontal scrollbar:

screen shot 2016-09-14 at 19 32 11

screen shot 2016-09-14 at 19 32 40

### CODE REVIEW

**Comment by terw-dan** [comment]
CR :+1:

**Comment by terw-dan** [comment]
Acceptance. When running in a very small viewport
image
The colored bullet has a strange alignment. Also the texts are missing (is this intended?). 
image
Also on wider viewports.

**Comment by atimmer** [comment]
CR & Acceptance Done 👍🏻

**Comment by afercia** [comment]
> The colored bullet has a strange alignment. Also the texts are missing (is this intended?). 
haven't touched that part :) yep the responsive view would need further improvements.

**Comment by atimmer** [comment]
For reference: https://github.com/Yoast/yoast-components/issues/76

**Pull request merged**
